/*
 * This code was generated by a tool.
 * Modified to use local proxy in development
 */

// Use local proxy to avoid CORS issues in development
const url = "/spwg-api/";
const jsonCT = new Headers();
jsonCT.append('Content-Type', 'application/json');

function jsonRequest(method, args=[], kwargs={}) {
    return new Promise((resolve, reject) => {
        fetch(url, {
            method: 'POST',
            headers: jsonCT,
            credentials: 'include',
            body: JSON.stringify({method,args,kwargs,"version":2})
        }).then(response => {
            if (response.status == 200) {
                response.json().then(res => {
                    if (!res.success) {
                        console.log(res.error + ": " + res.error_message);
                        reject(res.error);
                    } else {
                        resolve(res.result);
                    }
                });
            } else {
                reject(status);
            }                
        }).catch(error => reject(error));
    });
}


export function getMethods() { return jsonRequest('getMethods'); }
export function getDetails() { return jsonRequest('getDetails'); }
export function hasCapability(capability) { return jsonRequest('hasCapability', [capability]); }
export function getWordCount(number) { return jsonRequest('getWordCount', [number]); }
export function convertToWords(number) { return jsonRequest('convertToWords', [number]); }
export function generateWithLength(length) { return jsonRequest('generateWithLength', [length]); }
export function convertToNumber(words) { return jsonRequest('convertToNumber', [words]); }
export function timecalc(count, tests) { return jsonRequest('timecalc', [count, tests]); }
export function gen_password_text(password, bits) { return jsonRequest('gen_password_text', [password, bits]); }
export function gen_security_text(count) { return jsonRequest('gen_security_text', [count]); }
export function frombits(inputentropy) { return jsonRequest('frombits', [inputentropy]); }
export function fromlengthbatch(inputentropy, passwordcount) { return jsonRequest('fromlengthbatch', [inputentropy, passwordcount]); }
export function fromlength(inputentropy) { return jsonRequest('fromlength', [inputentropy]); }
export function frommax(inputentropy) { return jsonRequest('frommax', [inputentropy]); }
export function tonumber(inputwords) { return jsonRequest('tonumber', [inputwords]); }
export function towords(inputnumber) { return jsonRequest('towords', [inputnumber]); }
export function randseg(segtype) { return jsonRequest('randseg', [segtype]); }
export function genapw(pwtype, length) { return jsonRequest('genapw', [pwtype, length]); }
export function apwg(pwtype, length) { return jsonRequest('apwg', [pwtype, length]); }
export function pwgen() { return jsonRequest('pwgen'); }
